# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Firebase Chat' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Firebase Chat
pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'MessageKit'
  target 'Firebase ChatTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Firebase ChatUITests' do
    # Pods for testing
  end

end
