# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Firebase Chat' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Firebase Chat
  # pod 'Firebase/Analytics'
  pod 'Firebase/Core'
  # pod 'Firebase/Core', '~> 6.6.7'
  pod 'Firebase/Database'
  # pod 'Firebase/Database', '~> 6.2.0'

end
