# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Firebase Chat' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Firebase Chat
pod 'Firebase/Core'
pod 'MessageKit'
pod 'Firebase/Database'
end
