# Uncomment the next line to define a global platform for your project
 platform :ios, '13.5'

target 'FirebasePractice' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FirebasePractice

pod 'Firebase/Analytics'


# add pods for any other desired Firebase products
pod 'Firebase/Core'
pod 'Firebase/Database'


# https://firebase.google.com/docs/ios/setup#available-pods

end
