# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FirebaseChatApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FirebaseChatApp
pod 'Firebase/Analytics'
pod 'MessageKit'
  target 'FirebaseChatAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FirebaseChatAppUITests' do
    # Pods for testing
  end

end
