# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Firebase_Chat' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Firebase_Chat

  pod 'Firebase/Analytics'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'MessageKit'

end

