# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FirebaseMessages' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FirebaseMessages
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'MessageKit'

end
