# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

# add pods for desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods

target 'FirebaseChat' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FirebaseChat
pod 'FirebaseCore', :git => 'https://github.com/firebase/firebase-ios-sdk.git', :branch => 'master'
pod 'FirebaseFirestore', :git => 'https://github.com/firebase/firebase-ios-sdk.git', :branch => 'master'
pod 'Firebase/Database'


end
