# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FirebaseChat' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FirebaseChat
  pod 'Firebase/Database'

  target 'FirebaseChatTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FirebaseChatUITests' do
    # Pods for testing
  end

end
